### ISSUE TITLE
find-specs broken - no way to extract stage 3 TC39 proposals

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1031]
TC39 stage 3 proposals are extracted from a rendered version of a `README.md` file fetched from GitHub with JSDOM. GitHub now seems to be making an extensive use of React to load the contents of the page dynamically, and this does not seem to work well with JSDOM. The find-specs script fails accordingly as it cannot find the `<table>` elements.

We could perhaps to switch to Puppeteer. Or retrieve the markdown itself and parse it or render it ourselves with some dedicated library.

(Also note the default branch name was renamed to `main` but the URL of the README file is not the cause of the issue).

**Comment by dontcallmedom** [comment]
switching to puppeteer would allow to revisit the use of spec-generator we took in #944

**Comment by tidoust** [comment]
Switched to Puppeteer.
