### ISSUE TITLE
Consider adding AOM specs

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1088]
Via #1008. The Alliance for Open Media has developed a number of specs, some of which are supported in browsers:

- [ ] HDR10+ AV1 Metadata Handling: https://aomediacodec.github.io/av1-hdr10plus/
- [ ] AV1 Codec ISO Media File Format Binding: https://aomediacodec.github.io/av1-isobmff/
- [ ] AV1 Bitstream & Decoding Process: https://aomediacodec.github.io/av1-spec/
- [ ] Carriage of AV1 in MPEG-2 TS: https://aomediacodec.github.io/av1-mpeg2-ts/
- [x] AV1 Image File Format (AVIF) (implemented in all three browser engines!): https://aomediacodec.github.io/av1-avif/
- [ ] RTP Payload Format For AV1: https://aomediacodec.github.io/av1-rtp-spec/
- [ ] AOMedia Film Grain Synthesis 1 (AFGS1): https://aomediacodec.github.io/afgs1-spec/

Note: some of these specs use Bikeshed or ReSpec but the canonical representation of the main AV1 spec is a PDF file, and the last few drafts follow some more ad-hoc HTML format that may require code changes in browser-specs and/or Reffy.

**Comment by foolip** [comment]
Yes please, AVIF in particular would help https://github.com/web-platform-dx/web-features/pull/399.

**Comment by tidoust** [comment]
Also on the todo list: code needs to be updated to extract and accept the "Final Deliverable" status of the spec, not to claim that they are Editor's Drafts.
