### ISSUE TITLE
Consider web font/image/media formats

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1089]
Via #1008. Consider adding font/image/media formats commonly supported on the web. The main difficulty is that these specifications do not follow a well-known format.

The list includes:
- [x] GIF
- [x] JPEG
- [x] [WebP Container Specification](https://developers.google.com/speed/webp/docs/riff_container)
- [x] [WebP Lossless Bitstream](https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification)
- [x] [COLR — Color Table](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/colr)
- [x] GLSL: Shading language for WebGL.
- [x] glTF: File format for 3D models
- Various more image, video, audio, font, etc. formats.

**Comment by tidoust** [comment]
For WebP, see dedicated issue #1109

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/580 is blocked on this, and is additionally made complicated by the fact that the JEPG XL spec doesn't have a public URL.

**Comment by tidoust** [comment]
> [web-platform-dx/web-features#580](https://github.com/web-platform-dx/web-features/pull/580) is blocked on this, and is additionally made complicated by the fact that the JEPG XL spec doesn't have a public URL.

I think we can take the same approach as [Specref](https://www.specref.org/?q=jpeg%20xl), which links to the spec page on the ISO web site for ISO/IEC standards. For JPEG XL support in browsers, we probably want to document the file format: [iso18181-2](https://www.iso.org/standard/85253.html), not the core coding system (or list both, but the file format seems the right entry point). I created #1191 to discuss adding specs that don't have published versions to browser-specs.

([Can I Use](https://caniuse.com/jpegxl) rather links to the [JPEG Documentation page](https://jpeg.org/jpegxl/documentation.html), which seems suboptimal: the page does not linnk to the ISO web site)

**Comment by tidoust** [comment]
The list now contains the formats identified in this issue. A couple of notes:

- For JPEG, the reference is to [`iso10918-5`](https://www.iso.org/standard/54989.html), done in #1237
- For GLSL, the spec actually added is [OpenGL ES Shading Language](https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html) (ESSL) because I believe that's what WebGL actually uses, done in #1238
- For COLR, [`iso14496-22`](https://www.iso.org/standard/87621.html) was used, done in #1211

I'm closing the issue accordingly. Additional formats may be worth adding. Let's handle them through dedicated issues and pull requests!
