### ISSUE TITLE
Consider adding WebP specs

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#1109]
Similar to https://github.com/w3c/browser-specs/issues/1088, consider listing https://developers.google.com/speed/webp/ or the specs linked therein:

- https://developers.google.com/speed/webp/docs/riff_container (container)
- https://datatracker.ietf.org/doc/rfc6386/ (VP8 lossy mode)
- https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification (lossless mode)

**Comment by dontcallmedom** [comment]
For WebP specs, rather than the developers.google.com, https://datatracker.ietf.org/doc/draft-zern-webp/ would seem a better fit for browser-specs.

**Comment by foolip** [comment]
Nice find! I've sent https://github.com/w3c/browser-specs/pull/1120.
