### ISSUE TITLE
Consider adding iFrame credentialless API

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#1144]
We currently don't render a specification on MDN because this spec is not in browser-specs.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/credentialless
https://developer.mozilla.org/en-US/docs/Web/API/Window/credentialless

Compat data has been submitted (partially) manually and not through the "webref -> bcd-collector -> bcd" pipeline, because the IDL for this spec is not in webref. It seems to be supported in Chrome already, though.

I don't know what it means to have "no real group name". Can this be fixed? 

```
"https://wicg.github.io/anonymous-iframe/": {
      "lastreviewed": "2023-11-01",
      "comment": "no real group name in w3c.json file"
    },
```

**Comment by dontcallmedom** [comment]
re fixing it, there is a pending PR for that https://github.com/WICG/anonymous-iframe/pull/18

With that said, this shouldn't be a blocker for adding the spec to browser-specs, merely an inconvenience; and I agree that with it shipping in Chrome, adding it would be good

**Comment by Elchi3** [comment]
> (thinking more broadly if somewhat handwaving-ly - maybe the pipeline you've put in place to track new features in browser releases could also feed updates to browser-specs?)

Well, currently the collector relies on webref (and therefore on browser-specs) to collect new features for a browser release. So the feeding is primary in this direction. However, if we find out (totally manually by looking at release notes for example) that there are more things shipping not found by the collector then we of course start investigating reasons why it wasn't coming through the collector. 

At that point I would file an issue here (like this one). I'm not quite sure how feeding in this direction could be automated, though. I think we will have a bit more a structured approach to check how much was not proposed by the collector and why. I did an analysis with Chris for Chrome 120 where we also identified some specs missing and I will surely do such analysis again to improve the collector continuously https://github.com/mdn/browser-compat-data/pull/21148#issuecomment-1814638269 

So, yes, in a sense we will try to feed back into this project, but for the moment that is manual analysis work. If you have more thoughts on how to improve this, let me know :)

**Comment by dontcallmedom** [comment]
that sounds right; I guess what  I have a in mind would be a job in browser-specs that looks at the machine readable feature trains of browsers and somehow manage to identify which specs they come from and thus may need to be added to browser-specs. We have some basis for this already in the [`find-specs.js` script](https://github.com/w3c/browser-specs/blob/85a2ad6986a4723a6e890a8ef4fb0f26218bdccc/src/find-specs.js#L118); anyway, that's thinking aloud at this point, may be worth turning this into an issue when the idea firms up.

**Comment by teoli2003** [comment]
> that looks at the machine-readable feature trains of browsers and somehow manages to identify which specs

I have a tool (WIP) that classifies new features supported by a browser (from bcd) by spec, leaving a set of unclassified ones. We want to use this to generate PRs with a description like https://github.com/mdn/browser-compat-data/pull/21148#issuecomment-1805302266 for an example: features from not-listed spec should be in this section (much shorter already, and we work in having better coverage): ![Capture d’écran 2023-11-30 à 15 04 42](https://github.com/w3c/browser-specs/assets/1466293/387ca597-868e-4e8d-ae60-e963d15d667c)
