### ISSUE TITLE
Merchant Validation

### ISSUE THREAD

**Issue by skyclouds2001** [w3c/browser-specs#1162]
the spec https://w3c.github.io/merchant-validation/, I'm not sure if it is still a part of standard, and should it added to the `specs.json`?

coming from https://github.com/mdn/browser-compat-data/pull/21738

**Comment by tidoust** [comment]
I created #1163 to add the spec to the list. It hadn't been included because it indeed documents a deprecated API and we didn't have a good way to represent that status in browser-specs when we first bumped into it.

**Comment by tidoust** [comment]
Spec added to the list, released in [web-specs@v2.76.0](https://www.npmjs.com/package/web-specs/v/2.76.0)
