### ISSUE TITLE
How to add ISO/IEC specs

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1191]
Via #1089. ISO/IEC standards such as [JPEG XL](https://www.iso.org/standard/85253.html) do not have a public specification. They all have a "canonical" page on the ISO web site though, which seems a good entry point for the spec. That URL is also the one [used in Specref](https://www.specref.org/?q=jpeg%20xl).

Now, all entries in browser-specs so far target actual specs. Question is: how should we add ISO/IEC entries to browser-specs?

A clean solution would probably be to use the ISO page URL as the canonical URL and **not to set** the `nightly` property, because there are no public spec to point at. That would break the schema though as `nightly` is mandatory, and would likely require updates to the code of projects that currently consume browser-specs data as these projects may expect `nightly.url` to be always set.

A non-breaking solution would be to use the ISO page URL as the canonical URL and as the `nightly.url` URL. That's less clean but most code that uses browser-specs data today should continue to run. Well, Reffy may still need to learn to skip `iso.org` URLs.

Overall, choice seems to be between a major bump and a minor bump. The major bump approach is more painful but has the advantage of making things explicit. The minor bump is easier but has the drawback of hiding the fact that we may not have a published version of the spec.

**Comment by dontcallmedom** [comment]
I prefer the major bump approach ("the future is longer than the past", he said optimistically)

**Comment by tidoust** [comment]
Corresponding updates to code and list made, and new major versions released (already deployed in web-features and browser-compat-data, [pending PR for Yari](https://github.com/mdn/yari/pull/10478)). I'll update Reffy accordingly.
