### ISSUE TITLE
Consider short titles

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#12]
See discussion in https://github.com/w3c/browser-specs/issues/5#issue-567897765

It seems possible to compute a default shorter title (dropping words such as "Level" or "Module"), but that won't work in all cases. Ideally, that information would be defined in the spec, and would be tracked by the W3C API and Specref so that we don't have to do it here.

**Comment by tabatkins** [comment]
Yeah, I'm happy to add a `Short Title` metadata to Bikeshed, which'll be communicated via a `<meta>` in the spec which can be picked up by the crawler.

In the absence of that, it looks like just literally dropping the words "Level", "Module", or "Specification" from the long title works out pretty great - I just tried it out and didn't spot a single spec title that is messed up by this.  (Possibly also "Standard", but that's only used by WHATWG specs and their titles tend to be short anyway, so we probably don't need to worry about it.)

So, with that heuristic applied by default, and an optional shortTitle key for the handful of specs that need something shorter (CSS has several where the full title is wordy), I think we could deploy this today, and then start relying on Bikeshed metadata afterward.

**Comment by tabatkins** [comment]
Yeah, the Short Titles in Shepherd are manually maintained, it's just one of the fields you put in for the entry.

**Comment by tidoust** [comment]
Comparing newly generated short titles in browser-specs with the list of short titles in Shepherd, I end up with the following differences (first title is the generated one in browser-specs, second the short title in Shepherd).

Need a manual entry in `specs.json`:
- [ ] [css-gcpm-4](https://drafts.csswg.org/css-gcpm-4/) - "CSS Generated Content for Paged Media 4" compared to "CSS GCPM 4"
- [ ] [css-multicol-2](https://drafts.csswg.org/css-multicol-2/) - "CSS Multi-column Layout 2" compared to "CSS Multicol 2"
- [ ] [css-size-adjust-1](https://drafts.csswg.org/css-size-adjust-1/) - "CSS Mobile Text Size Adjustment 1" compared to "CSS Size Adjustment 1"
- [ ] [compositing-2](https://drafts.fxtf.org/compositing-2/) - "Compositing and Blending 2" compared to "Compositing 2"
- [ ] [background-sync](https://wicg.github.io/background-sync/spec/) - "Web Background Synchronization" compared to "Background Sync"
- [ ] [sms-one-time-codes](https://wicg.github.io/sms-one-time-codes/) - "Origin-bound one-time codes delivered via SMS" compared to "SMS One-Time Codes"
- [ ] [compositing-1](https://www.w3.org/TR/compositing-1/) - "Compositing and Blending 1" compared to "Compositing 1"
- [ ] [css-backgrounds-3](https://www.w3.org/TR/css-backgrounds-3/) - "CSS Backgrounds and Borders 3" compared to "CSS Backgrounds 3"
- [ ] [css-cascade-3](https://www.w3.org/TR/css-cascade-3/) - "CSS Cascading and Inheritance 3" compared to "CSS Cascading 3"
- [ ] [css-cascade-4](https://www.w3.org/TR/css-cascade-4/) - "CSS Cascading and Inheritance 4" compared to "CSS Cascading 4"
- [ ] [css-conditional-4](https://www.w3.org/TR/css-conditional-4/) - "CSS Conditional Rules 4" compared to "CSS Conditional 4"
- [ ] [css-flexbox-1](https://www.w3.org/TR/css-flexbox-1/) - "CSS Flexible Box Layout 1" compared to "CSS Flexbox 1"
- [ ] [css-gcpm-3](https://www.w3.org/TR/css-gcpm-3/) - "CSS Generated Content for Paged Media" compared to "CSS GCPM 3"
- [ ] [css-images-3](https://www.w3.org/TR/css-images-3/) - "CSS Image Values and Replaced Content 3" compared to "CSS Images 3"
- [ ] [css-images-4](https://www.w3.org/TR/css-images-4/) - "CSS Image Values and Replaced Content 4" compared to "CSS Images 4"
- [ ] [css-lists-3](https://www.w3.org/TR/css-lists-3/) - "CSS Lists and Counters 3" compared to "CSS Lists 3"
- [ ] [css-logical-1](https://www.w3.org/TR/css-logical-1/) - "CSS Logical Properties and Values 1" compared to "CSS Logical Properties 1"
- [ ] [css-multicol-1](https://www.w3.org/TR/css-multicol-1/) - "CSS Multi-column Layout 1" compared to "CSS Multicol 1"
- [ ] [css-sizing-3](https://www.w3.org/TR/css-sizing-3/) - "CSS Intrinsic & Extrinsic Sizing 3" compared to "CSS Sizing 3"
- [ ] [css-sizing-4](https://www.w3.org/TR/css-sizing-4/) - "CSS Box Sizing 4" compared to "CSS Sizing 4"
- [ ] [css-ui-3](https://www.w3.org/TR/css-ui-3/) - "CSS3 UI" compared to "CSS User Interface 3"
- [ ] [css-values-3](https://www.w3.org/TR/css-values-3/) - "CSS Values and Units 3" compared to "CSS Values 3"
- [ ] [css-values-4](https://www.w3.org/TR/css-values-4/) - "CSS Values and Units 4" compared to "CSS Values 4"
- [ ] [css-variables-1](https://www.w3.org/TR/css-variables-1/) - "CSS Custom Properties for Cascading Variables 1" compared to "CSS Variables 1"
- [ ] [fetch-metadata](https://www.w3.org/TR/fetch-metadata/) - "Fetch Metadata Request Headers" compared to "Fetch Metadata"
- [ ] [fill-stroke-3](https://www.w3.org/TR/fill-stroke-3/) - "CSS Fill and Stroke 3" compared to "Fill & Stroke"
- [ ] [IndexedDB-2](https://www.w3.org/TR/IndexedDB-2/) - "Indexed Database API 2.0" compared to "Indexed DB 2"
- [ ] [payment-method-basic-card](https://www.w3.org/TR/payment-method-basic-card/) - "Payment Method: Basic Card" compared to "Basic Card"
- [ ] [SRI](https://www.w3.org/TR/SRI/) - "Subresource Integrity" compared to "SRI"
- [ ] [webrtc-stats](https://www.w3.org/TR/webrtc-stats/) - "Identifiers for WebRTC's Statistics API" compared to "WebRTC Statistics"
- [ ] [WOFF2](https://www.w3.org/TR/WOFF2/) - "WOFF File Format 2.0" compared to "WOFF 2.0"

Maybe worth a manual entry in `specs.json`:
- [ ] [css-highlight-api-1](https://drafts.csswg.org/css-highlight-api-1/) - "CSS Custom Highlight API 1" compared to "CSS Highlight API 1"
- [ ] [css-box-3](https://www.w3.org/TR/css-box-3/) - "CSS Box Model 3" compared to "CSS Box 3"
- [ ] [css-box-4](https://www.w3.org/TR/css-box-4/) - "CSS Box Model 4" compared to "CSS Box 4"
- [ ] [css-easing-1](https://www.w3.org/TR/css-easing-1/) - "CSS Easing Functions 1" compared to "CSS Easing 1"
- [ ] [css-ruby-1](https://www.w3.org/TR/css-ruby-1/) - "CSS Ruby Layout 1" compared to "CSS Ruby 1"
- [ ] [css-ui-4](https://www.w3.org/TR/css-ui-4/) - "CSS Basic User Interface 4" compared to "CSS User Interface 4"
- [ ] [css3-conditional](https://www.w3.org/TR/css3-conditional/) - "CSS Conditional Rules 3" compared to "CSS Conditional 3"
- [ ] [screen-orientation](https://www.w3.org/TR/screen-orientation/) - "The Screen Orientation API" compared to "Screen Orientation"

Close, often due to presence/absence of level, difference seems ignorable:
- [ ] [console](https://console.spec.whatwg.org/) - "Console" compared to "Console Standard"
- [ ] [fetch](https://fetch.spec.whatwg.org/) - "Fetch" compared to "Fetch Standard"
- [ ] [html](https://html.spec.whatwg.org/multipage/) - "HTML" compared to "HTML 5"
- [ ] [layers](https://immersive-web.github.io/layers/) - "WebXR Layers API 1" compared to "WebXR Layers 1"
- [ ] [url](https://url.spec.whatwg.org/) - "URL" compared to "URL Standard"
- [ ] [css-parser-api](https://wicg.github.io/css-parser-api/) - "CSS Parser API" compared to "CSS Parser API 1"
- [ ] [webusb](https://wicg.github.io/webusb/) - "WebUSB API" compared to "WebUSB"
- [ ] [CSP3](https://www.w3.org/TR/CSP3/) - "Content Security Policy 3" compared to "Content Security Policy"
- [ ] [css-animation-worklet-1](https://www.w3.org/TR/css-animation-worklet-1/) - "CSS Animation Worklet API" compared to "CSS Animation Worklet 1"
- [ ] [css-color-adjust-1](https://www.w3.org/TR/css-color-adjust-1/) - "CSS Color Adjust 1" compared to "CSS Color Adjust"
- [ ] [css-overscroll-1](https://www.w3.org/TR/css-overscroll-1/) - "CSS Overscroll Behavior 1" compared to "CSS Overscroll Behavior"
- [ ] [css-page-floats-3](https://www.w3.org/TR/css-page-floats-3/) - "CSS Page Floats" compared to "CSS Page Floats 3"
- [ ] [css-rhythm-1](https://www.w3.org/TR/css-rhythm-1/) - "CSS Rhythmic Sizing" compared to "CSS Rhythmic Sizing 1"
- [ ] [css-scrollbars-1](https://www.w3.org/TR/css-scrollbars-1/) - "CSS Scrollbars 1" compared to "CSS Scrollbars"
- [ ] [css-speech-1](https://www.w3.org/TR/css-speech-1/) - "CSS Speech" compared to "CSS Speech 1"
- [ ] [css-style-attr](https://www.w3.org/TR/css-style-attr/) - "CSS Style Attributes" compared to "CSS Style Attributes 1"
- [ ] [css-tables-3](https://www.w3.org/TR/css-tables-3/) - "CSS Table 3" compared to "CSS Tables 3"
- [ ] [css-transitions-1](https://www.w3.org/TR/css-transitions-1/) - "CSS Transitions" compared to "CSS Transitions 1"
- [ ] [css3-mediaqueries](https://www.w3.org/TR/css3-mediaqueries/) - "Media Queries" compared to "Media Queries 3"
- [ ] [cssom-1](https://www.w3.org/TR/cssom-1/) - "CSSOM" compared to "CSSOM 1"
- [ ] [permissions](https://www.w3.org/TR/permissions/) - "Permissions" compared to "Permissions API"
- [ ] [resize-observer-1](https://www.w3.org/TR/resize-observer-1/) - "Resize Observer" compared to "Resize Observer 1"
- [ ] [service-workers-1](https://www.w3.org/TR/service-workers-1/) - "Service Workers 1" compared to "Service Workers"
- [ ] [web-animations-1](https://www.w3.org/TR/web-animations-1/) - "Web Animations" compared to "Web Animations 1"
- [ ] [webaudio](https://www.w3.org/TR/webaudio/) - "Web Audio API" compared to "Web Audio"

**Comment by tidoust** [comment]
PR #120 adds short titles for specs in the first list. I propose not to do anything for the "maybe" and "ignorable" lists for now (that is, until someone explicitly asks for them to be covered) on the grounds that we probably want to keep things as automated as possible and changes seem minor.

**Comment by tidoust** [comment]
Short titles released in [v1.10.0](https://github.com/w3c/browser-specs/releases/tag/1.10.0). I'm closing down this issue. I suggest handling remaining discrepancies mentioned above on a case by case basis.

@tabatkins Please ping if you add a "Short title" tag to Bikeshed.
