### ISSUE TITLE
Add COLRv1 spec

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#1209]
COLRv1 is format of modern color fonts, and is supported by Chrome and is behind a flag in Firefox:
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#browser_compatibility

The best spec link for this that I know of is https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/colr

@drott is that the most appropriate spec link, or is there a more official one? ISO is OK even if it's behind a paywall.

**Comment by dontcallmedom** [comment]
IIUC, this should eventually land in [ISO/IEC AWI 14496-22](https://www.iso.org/en/standard/87621.html), per
> The next version of the OpenType spec will be version 1.9.1. An alpha release is being published to provide opportunity for wide review […] editorial [were] changes made to synchronize with the working draft for the 5th edition of ISO/IEC 14496-22, Open Font Format. 
[OpenType 1.9.1 Alpha Review](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha)

**Comment by foolip** [comment]
@drott thanks for https://github.com/mdn/browser-compat-data/pull/22231, I've merged that and will update the comment for the spec exception here.

**Comment by dontcallmedom** [comment]
I think we can already refer to the in-progress [ISO/IEC AWI 14496-22](https://www.iso.org/en/standard/87621.html) 5th edition as being the canonical URL for this work; since it's a WIP behind a paywall anyway, there is limited risk it would create confusion IMO

**Comment by foolip** [comment]
Cool, I've sent https://github.com/w3c/browser-specs/pull/1211.

**Comment by drott** [comment]
> It sounds like we wait until ISO releases 1.9.1 if that includes important updates to COLRv1.

Just for future reference, 1.9.1 is a version number of Microsoft's OpenType spec. [ISO/IEC AWI 14496-22](https://www.iso.org/en/standard/87621.html) 5th edition is the correct name and version/edition for the ISO OFF side of things.
