### ISSUE TITLE
Filter changelog

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/browser-specs#122]
The changes in the past few releases were a mix of actual new specs being tracked, and tooling around spec tracking.

It would be best if the changelog could be automatically filtered (e.g. using some labels) to only report package-relevant changes (i.e. specs being added, removed or updated).

**Comment by tidoust** [comment]
Closing this issue as we no longer maintain a changelog at the repo level. It would be interesting to maintain a changelog for the published data. Tracked in #770.
