### ISSUE TITLE
Add new spec: Device Attributes API

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1274]
### URL

https://wicg.github.io/WebApiDevice/device_attributes/

### Rationale

- [Shipping in Chrome](https://chromestatus.com/feature/5694001745231872)
- List already contains the [Managed Configuration API](https://wicg.github.io/WebApiDevice/managed_config/)

(One question is whether the "browser" category is the right one for "managed" APIs, but that's what we have for the Managed Configuration API)

### Additional properties

```json
{
  "shortname": "device-attributes",
  "nightly": {
    "sourcePath": "device_attributes/index.bs"
  }
}
```

**Comment by dontcallmedom** [comment]
@browser-specs-bot pr

**Comment by dontcallmedom** [comment]
was that the wrong magic? https://github.com/w3c/browser-specs/actions/runs/8435385666

**Comment by tidoust** [comment]
I think being organization owners is not enough to be considered owners of the repository. I tried to add us as "admin" of the repos, but that does not seem to change anything. Perhaps the code should rather run on [MEMBER](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) even though that's a bit loose (or hardcode our names).

**Comment by dontcallmedom** [comment]
MEMBER would work, esp if we keep the PR process as a safeguard to write access

**Comment by dontcallmedom** [comment]
@browser-specs-bot pr

**Comment by dontcallmedom** [comment]
`git: 'co' is not a git command`

**Comment by tidoust** [comment]
Pff, why don't aliases propagate?

**Comment by dontcallmedom** [comment]
@browser-specs-bot pr

**Comment by dontcallmedom** [comment]
@browser-specs-bot pr

**Comment by tidoust** [comment]
No, that still won't work ;) Need to understand how to push with `gh` in a context that is not my local context ;)

**Comment by tidoust** [comment]
Spec added. Closing issue manually, see #1282 to make that automatic when PR is merged.
