### ISSUE TITLE
Add new spec: A Well-Known URL for Passkey Endpoints

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/browser-specs#1291]
### URL

https://w3c.github.io/webappsec-passkey-endpoints/passkey-endpoints.html

### Rationale

Adopted by the WebAppSec Working Group

### Additional properties

```json
{"nightly":{"sourcePath": "passkey-endpoints.bs"}}
```

**Comment by tidoust** [comment]
@browser-specs-bot pr

**Comment by tidoust** [comment]
For some reason, the job was skipped. Perhaps the job does not see me as "MEMBER"? @dontcallmedom, could you give it a try yourself?

**Comment by dontcallmedom** [comment]
@browser-specs-bot pr

**Comment by dontcallmedom** [comment]
it looks like @browser-specs-bot is rebelling against its creator

**Comment by tidoust** [comment]
I'm going to reuse this issue to make tests. You may ignore the comments (and any created PR if one gets created, although none should be in practice, since the spec is now in `specs.json`).

@browser-specs-bot pr

**Comment by tidoust** [comment]
OK, that worked (and didn't create a PR, which is good too!). I hadn't realized that my W3C membership on GitHub was "private". Actually, I hadn't paid attention to that setting until today. ;)

I suspect that the job lies to preserve my privacy (don't know who that person is, certainly not a member!). That makes sense. Making my membership "public" solved the issue.
