### ISSUE TITLE
Add new spec: Extending Storage Access API (SAA) to non-cookie storage

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1318]
### URL

https://privacycg.github.io/saa-non-cookie-storage/

### Rationale

Via #1317:

* This was adopted by PrivacyCG for incubation and is shipping in Chrome 125.
* Needed for https://github.com/mdn/browser-compat-data/pull/22977 https://github.com/mdn/browser-compat-data/pull/22978

### Additional properties

```json
{
  "shortTitle": "Extending Storage Access API to non-cookie storage"
}
```

**Comment by arichiv** [comment]
Added w3c.json, thanks for the pointer!

**Comment by arichiv** [comment]
@browser-specs-bot pr

**Comment by tidoust** [comment]
@browser-specs-bot pr
