### ISSUE TITLE
Consider building an HTTP cache stored as a GitHub cache

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1357]
Via @dontcallmedom in https://github.com/w3c/browser-specs/issues/1356#issuecomment-2153341294:

> While we're looking at the cg-monitor, another idea from there maybe worth exploring is to build an HTTP cache and reuse it from one job to the next with GitHub caches.

**Comment by dontcallmedom** [comment]
since the changes seem to have been sufficient, and since the HTTP cache in CG monitor turns out flaky at best, let's close this issue; we can always re-consider if/when we get similar challenges in the future
