### ISSUE TITLE
Stop loading CSS stylesheets

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#1358]
Via https://github.com/w3c/browser-specs/pull/1356#issuecomment-2154187664

The reason why CSS stylesheets are not currently intercepted is that "Respec dynamically loads a few CSS resources, and intercepting them could perhaps impact the rest of the generation", as noted in:
https://github.com/w3c/reffy/blob/a0c9bdabb31f4175fcbf99267a0b306140f849a2/src/lib/util.js#L296

... but I doubt that's true (if it ever was). And, as noted by @dontcallmedom in https://github.com/w3c/browser-specs/pull/1356#issuecomment-2154191188, we may return an empty stylesheet if needed.

**Comment by dontcallmedom** [comment]
This was done
