### ISSUE TITLE
Add new spec: RFC918 - Extensible Prioritization Scheme for HTTP

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#1383]
### URL

https://www.rfc-editor.org/rfc/rfc9218

### Rationale

Implemented in Gecko 128: https://bugzilla.mozilla.org/show_bug.cgi?id=1865040
Implemented in Chromium 124: https://chromestatus.com/feature/5109106573049856

### Additional properties

```json
{}
```

**Comment by Elchi3** [comment]
@browser-specs-bot pr

**Comment by dontcallmedom** [comment]
@browser-specs-bot pr
