### ISSUE TITLE
ECMA specs not in scope?

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#139]
Hey, I'm looking at this project as I evaluate how to make MDN specification sections better.

Currently, MDN spec data lives here: https://github.com/mdn/kumascript/blob/master/macros/SpecData.json
The list is not very well maintained, but it does have ECMA specs.

As far as I can tell, there are no ECMA specs in this project. Why not?

**Comment by dontcallmedom** [comment]
The lack of ECMA specs was noted in #58 - I think we'd be happy to add them, but we had lacked cycles and primary motivation; re-use in MDN sounds like a great motivation, so it would just be a matter of finding cycles, which I think we can aim to do in the near future.

Looking at the MDN data, I see:
* a number of different ECMA 402 versions
* different versions of the internationalization API
* async/await
* async iteration

Would that be enough as a starting point, or would you also be looking to cover a broader set of specs (e.g. all or a subset of the other TC39 proposals)?

**Comment by Elchi3** [comment]
It happens that features are in TC39 proposals for a while and already shipped in browsers, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#Specifications, or various Intl proposals. So, I guess, for MDN purposes, TC39 proposals would also be in scope. 

After a while the proposals are usually merged into the main specs, though. So having the main TC39 specs would be a great starting point indeed.

Thanks!
