### ISSUE TITLE
Add new spec: Private Aggregation API

### ISSUE THREAD

**Issue by alexmturner** [w3c/browser-specs#1450]
### URL

https://patcg-individual-drafts.github.io/private-aggregation-api/

### Rationale

This spec is an "individual draft" under the PATCG and is [shipped on Chrome](https://groups.google.com/a/chromium.org/g/blink-dev/c/8cKaLstq2QQ). This is in a similar state to Topics, which appears to be listed already. Thanks!

### Additional properties

```json
{
  "groups": [
    {
      "name": "Private Advertising Technology Community Group",
      "url": "https://www.w3.org/community/patcg/"
    }
  ],
  "standing": "pending"
}
```

**Comment by tidoust** [comment]
I added a few additional properties to fix the build (code does not know anything about the PAT CG and cannot get that info from the repository itself) and to flag the spec as ["pending"](https://github.com/w3c/browser-specs/?tab=readme-ov-file#standing) as done for the Topics API.

**Comment by tidoust** [comment]
@browser-specs-bot pr
