### ISSUE TITLE
WebGL extensions

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#156]
There are a lot of WebGL extensions that define bits of Web IDL, at some of which are implemented in browsers:
https://www.khronos.org/registry/webgl/extensions/

Adding all of these manually would be a bit tedious, is there another way we could handle these?

**Comment by dontcallmedom** [comment]
would the need be to (automatically) add "Khronos ratified WebGL Extensions", "Community approved WebGL Extensions" and "Draft WebGL Extensions"?

**Comment by foolip** [comment]
I would say all of them, as I assume some browser implements some extension from all three groups.
