### ISSUE TITLE
MathML title is... very special

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#168]
https://github.com/w3c/browser-specs/blob/7bc9c496e741e0fe657676012896a238b8238750/index.json#L632

This title, "An interoperable subset of Mathematical Markup Language (MathML) suitable for browsers 1st Edition", doesn't appear in https://mathml-refresh.github.io/mathml-core/. Where does it come from?

**Comment by tidoust** [comment]
[Source](https://github.com/w3c/browser-specs/blob/master/index.json#L633) is Specref, which indeed [has this weird title for the spec](https://www.specref.org/?q=mathml-core). I filed a pull request against Specref to have the title updated: https://github.com/tobie/specref/pull/626

**Comment by tidoust** [comment]
Fixed in Specref and in browser-specs, update released in [v1.17.0](https://github.com/w3c/browser-specs/releases/tag/1.17.0).

**Comment by foolip** [comment]
Thanks @tidoust!
