### ISSUE TITLE
Expose spec repository

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#19]
Tools may find it useful to get to the repository that hosts the specification. As with the spec title, 3 ways to determine the repo:

1. Get it from the W3C API for TR specs.
2. Get it from Specref for non-TR specs.
3. Fetch the spec and extract it from the HTML content, when possible

**Comment by dontcallmedom** [comment]
The spec dashboard has existing logic to [map editors draft urls to github repo](https://github.com/w3c/spec-dashboard/blob/master/fetch-data/group-repos.js#L65) which might serve as inspiration here (not sure yet if the spec dashboard could en up reusing data or code from browser-specs)

**Comment by foolip** [comment]
This would be useful for https://github.com/foolip/day-to-day/issues/85

**Comment by foolip** [comment]
I've also written code to map URLs to repos, search for `specrepo ` in https://github.com/foolip/day-to-day/blob/a508cc63a9b2c1ec43603ede29cd24227038edf2/build/specs.js

**Comment by tidoust** [comment]
Done and deployed in [v1.9.0](https://github.com/w3c/browser-specs/releases/tag/1.9.0) through a `repository` property under `nightly` (since the repository is associated with the nightly version)
