### ISSUE TITLE
Manage and expose related WPT folder

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#201]
It would be good to link specs to their test suite in WPT.

Most of that mapping info can likely be determined automatically by looking at `META.yml` files in WPT, and/or by searching for a link to the test suite in the spec itself.

Practically speaking, a script that runs weekly and creates PR automatically should do the trick.

**Comment by dontcallmedom** [comment]
Note `testpath` in https://github.com/foolip/day-to-day/blob/main/specs-fixes.json

**Comment by tidoust** [comment]
Looking at `META.yml` files works well for 220 entries. There are 30 other cases where I can map specs to folders based on the spec's shortname. TC39 specs, WebGL extensions, and the WebAssembly Core spec will have to be handled separately, since there test suites are not in WPT.

I identified 32 cases where I could map the spec to a WPT folder if the info there was correct. I prepared https://github.com/web-platform-tests/wpt/pull/26970 accordinly.

There would remain 43 specs that don't have test suites as far as I can tell. Here is the list:

<details><summary>List of specs that don't have known test suites</summary>

- `change-password-url` => [A Well-Known URL for Changing Passwords](https://w3c.github.io/webappsec-change-password-url/)
- `crash-reporting` => [Crash Reporting](https://wicg.github.io/crash-reporting/)
- `css-extensions-1` => [CSS Extensions](https://drafts.csswg.org/css-extensions-1/)
- `css-highlight-api-1` => [CSS Custom Highlight API Module Level 1](https://drafts.csswg.org/css-highlight-api-1/)
- `css-line-grid-1` => [CSS Line Grid Module Level 1](https://drafts.csswg.org/css-line-grid/)
- `css-nav-1` => [CSS Spatial Navigation Level 1](https://drafts.csswg.org/css-nav-1/)
- `css-nesting-1` => [CSS Nesting Module](https://drafts.csswg.org/css-nesting-1/)
- `css-page-floats-3` => [CSS Page Floats](https://drafts.csswg.org/css-page-floats/)
- `css-regions-1` => [CSS Regions Module Level 1](https://drafts.csswg.org/css-regions/)
- `css-rhythm-1` => [CSS Rhythmic Sizing](https://drafts.csswg.org/css-rhythm/)
- `file-system-access` => [File System Access](https://wicg.github.io/file-system-access/)
- `font-metrics-api-1` => [Font Metrics API Level 1](https://drafts.css-houdini.org/font-metrics-api-1/)
- `frame-timing` => [Frame Timing](https://wicg.github.io/frame-timing/)
- `gamepad-extensions` => [Gamepad Extensions](https://w3c.github.io/gamepad/extensions.html)
- `get-installed-related-apps` => [Get Installed Related Apps API](https://wicg.github.io/get-installed-related-apps/spec/)
- `graphics-aria-1.0` => [WAI-ARIA Graphics Module](https://w3c.github.io/graphics-aria/)
- `html-aam-1.0` => [HTML Accessibility API Mappings 1.0](https://w3c.github.io/html-aam/)
- `html-aria` => [ARIA in HTML](https://w3c.github.io/html-aria/)
- `image-resource` => [Image Resource](https://w3c.github.io/image-resource/)
- `infra` => [Infra Standard](https://infra.spec.whatwg.org/)
- `local-font-access` => [Local Font Access API](https://wicg.github.io/local-font-access/)
- `mathml-aam` => [MathML Accessiblity API Mappings 1.0](https://w3c.github.io/mathml-aam/)
- `mediacapture-automation` => [Media Capture Automation](https://w3c.github.io/mediacapture-automation/)
- `overscroll-scrollend-events` => [overscroll and scrollend events](https://wicg.github.io/overscroll-scrollend-events/)
- `payment-method-manifest` => [Payment Method Manifest](https://w3c.github.io/payment-method-manifest/)
- `performance-measure-memory` => [Measure Memory API](https://wicg.github.io/performance-measure-memory/)
- `private-click-measurement` => [Private Click Measurement](https://privacycg.github.io/private-click-measurement/)
- `resource-hints` => [Resource Hints](https://w3c.github.io/resource-hints/)
- `screen-fold` => [The Screen Fold API](https://w3c.github.io/screen-fold/)
- `selectors-nonelement-1` => [Non-element Selectors Module Level 1](https://drafts.csswg.org/selectors-nonelement/)
- `sms-one-time-codes` => [Origin-bound one-time codes delivered via SMS](https://wicg.github.io/sms-one-time-codes/)
- `svg-animations` => [SVG Animations Level 2](https://svgwg.org/specs/animations/)
- `svg-integration` => [SVG Integration](https://svgwg.org/specs/integration/)
- `svg-markers` => [SVG Markers](https://svgwg.org/specs/markers/)
- `svg-paths` => [SVG Paths](https://svgwg.org/specs/paths/)
- `svg-strokes` => [SVG Strokes](https://svgwg.org/specs/strokes/)
- `trace-context-1` => [Trace Context - Level 1](https://w3c.github.io/trace-context/)
- `uievents-code` => [UI Events KeyboardEvent code Values](https://w3c.github.io/uievents-code/)
- `uievents-key` => [UI Events KeyboardEvent key Values](https://w3c.github.io/uievents-key/)
- `web-share-target` => [Web Share Target API](https://w3c.github.io/web-share-target/)
- `webdriver-bidi` => [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/)
- `webpackage` => [Loading Signed Exchanges](https://wicg.github.io/webpackage/loading.html)
- `webrtc-ice` => [IceTransport Extensions for WebRTC](https://w3c.github.io/webrtc-ice/)
</details>

**Comment by tidoust** [comment]
Information in `META.yml` files has been updated through https://github.com/web-platform-tests/wpt/pull/26970, https://github.com/web-platform-tests/wpt/pull/26983 and https://github.com/web-platform-tests/wpt/pull/26997.

I'll craft a pull request to expose that information in browser-specs.

I note that some `META.yml` files in WPT link to 23 specs that do not exist in browser-specs. As far as I can tell, that is fine, because the specs do not meet our selection criteria. Here is the list:

<details><summary>List of WPT folders associated with specs that do not exist in browser-specs</summary>

- [`annotation-model`](https://www.w3.org/TR/annotation-model/) => not a browser spec
- [`annotation-protocol`](https://www.w3.org/TR/annotation-protocol/) => not a browser spec
- [`annotation-vocab`](https://www.w3.org/TR/annotation-vocab/) => not a browser spec
- [`apng`](https://wiki.mozilla.org/APNG_Specification) => not a "proper" spec
- [`css/CSS1`](https://www.w3.org/TR/CSS1/) => obsolete
- [`document-policy`](https://wicg.github.io/document-policy/) => in monitor list
- [`domxpath`](https://www.w3.org/TR/DOM-Level-3-XPath/) => obsolete
- [`dpub-aam`](https://w3c.github.io/dpub-aam/) => not a browser spec
- [`dpub-aria`](https://w3c.github.io/dpub-aria/) => not a browser spec
- [`editing`](https://w3c.github.io/editing/execCommand.html) => obsolete
- [`feature-policy`](https://wicg.github.io/feature-policy/) => obsolete
- [`html-longdesc`](https://www.w3.org/TR/html-longdesc/) => obsolete?
- [`merchant-validation`](https://w3c.github.io/merchant-validation/) => in monitor list
- [`native-io`](https://todo.github.io/native-io/) => no spec yet
- [`origin-isolation`](https://github.com/WICG/origin-isolation) => Monitor list
- [`raw-sockets`](https://github.com/WICG/raw-sockets/blob/master/docs/explainer.md) => Monitor list
- [`sanitizer-api`](https://wicg.github.io/sanitizer-api/) => Monitor list
- [`screen_enumeration`](https://webscreens.github.io/window-placement/) => Monitor list
- [`signed-exchange`](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html) => IETF spec
- [`storage/buckets`](https://github.com/WICG/storage-buckets) => Monitor list
- [`web-bundle`](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html) => IETF spec
- [`webrtc-extensions`](https://w3c.github.io/webrtc-extensions/) => Monitor list
- [`webvr`](https://immersive-web.github.io/webvr/spec/1.1/) => Obsolete
</details>
