### ISSUE TITLE
Number postfixes for WebGL extensions

### ISSUE THREAD

**Issue by saschanaz** [w3c/browser-specs#221]
* `EXT_disjoint_timer_query_webgl2`
* `OVR_multiview2`
* `WEBGL_compressed_texture_etc1`
 
I found some WebGL extensions have their numbers trimmed in browser-specs and webref. AFAIK those numbers are not about spec versions, so I think they should be kept.

**Comment by tidoust** [comment]
Same problem for the recently added `ecma-402` spec which ends up with a `seriesVersion` set to `402` and a series shortname set to `ecma`.
