### ISSUE TITLE
Add missing trailing slash to ED URL of CSS Scroll Anchoring

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#226]
The URL of the Editor's Draft of CSS Scroll Anchoring is `https://drafts.csswg.org/css-scroll-anchoring` but should rather be `https://drafts.csswg.org/css-scroll-anchoring/` (with a trailing slash) for consistency with all other cases.

The info comes from the W3C API, which extracted it from the published spec. It needs to be fixed in the [Editor's Draft itself](https://drafts.csswg.org/css-scroll-anchoring/)

**Comment by tidoust** [comment]
URL fixed in the ED in https://github.com/w3c/csswg-drafts/pull/5817.

@deniak, could you add the trailing slash in the W3C API?

**Comment by deniak** [comment]
@tidoust done!

**Comment by tidoust** [comment]
Picked up in https://github.com/w3c/browser-specs/commit/1609274bfd26236dd9341b51a21979ef414ed35f
