### ISSUE TITLE
Move SVG Path to monitor list?

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#247]
Triggered by https://github.com/w3c/webref/pull/108 and https://github.com/w3c/svgwg/issues/818

The spec re-defines IDL that is currently in SVG 2 spec and the [Status of This Document](https://svgwg.org/specs/paths/#sotd) section has a note to redirect to SVG 2 for now:

> This specification is an early draft that largely contains features that were dropped during the development of SVG 2. In the future, this specification will supercede the SVG 2 Paths chapter, however at this time the SVG 2 Paths chapter must be considered the normative definition for SVG Paths.

The IDL patch in webref excludes the IDL that the spec defines. Perhaps the spec should rather simply be dropped from browser-specs until the spec progresses?

**Comment by foolip** [comment]
https://github.com/w3c/svgwg/issues/818#issuecomment-781708454 is what made me shy away from just deleting the spec. That's the stuff in https://svgwg.org/specs/paths/#PathDataCatmullRomCommand. I'm not sure if that's implemented anywhere though, it would require a test case to check.
