### ISSUE TITLE
Incorrect URL for SVG2 spec

### ISSUE THREAD

**Issue by pyoor** [w3c/browser-specs#272]
The SVG2 spec appears to contain an invalid URL:
https://github.com/w3c/browser-specs/blob/9348454b6af843e79df6108fcd023cca59e25bd1/specs.json#L570

As the default is mutli-page, the URL likely should be https://www.w3.org/TR/SVG2/

**Comment by tidoust** [comment]
Ah, I understand why this may appear to be wrong but the string isn't meant to be a pure URL. It is a compact form for:

```json
{
  "url": "https://www.w3.org/TR/SVG2/",
  "multipage": true
}
```

The `multipage` flag tells the parsing code to look for additional page in the table of contents of the spec.

See [Compact form preferred](https://github.com/w3c/browser-specs/blob/master/CONTRIBUTING.md#compact-form-preferred) in the doc (which should be updated to mention that it also applies to `multipage`).

**Comment by tidoust** [comment]
> See Compact form preferred in the doc (which should be updated to mention that it also applies to multipage).

Done in https://github.com/w3c/browser-specs/commit/4f981521f4b680cc28eca0cc539f7fbe4e75fc06
