### ISSUE TITLE
Add Do-Not-Track spec

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/browser-specs#281]
https://www.w3.org/TR/tracking-dnt/ defines WebIDL fragments widely implemented; even though it's been made non-normative, it should probably still be part of browser-specs (as highlighted in #279)

**Comment by tidoust** [comment]
I'm fine with this but if the goal is to extract the IDL fragments, that is not going to work. The fact that the document is non-normative (in practice, the fact that `<body>` has an `informative` class) means that Reffy won't extract them.

(The IDL fragments also need to be fixed but that's a separate issue)

**Comment by dontcallmedom** [comment]
I guess the IDL extraction is something we'll need to consider in the context of reffy (maybe we can add an exception there if we really want the IDL extracted)

**Comment by tidoust** [comment]
Added to browser-specs, and released in [v1.35.0](https://github.com/w3c/browser-specs/releases/tag/1.35.0).
