### ISSUE TITLE
https://w3c.github.io/webrtc-identity/identity.html should be https://w3c.github.io/webrtc-identity/

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#284]
Reported by @sideshowbarker in https://github.com/mdn/browser-compat-data/pull/10060#issuecomment-825999347.

https://w3c.github.io/webrtc-identity/identity.html and https://w3c.github.io/webrtc-identity/ are the same. The reason we get the former is because https://www.w3.org/TR/webrtc-identity/ links to it.

Perhaps adding a redirect in https://github.com/w3c/webrtc-identity is the best way to achieve this.

**Comment by tidoust** [comment]
> The reason we get the former is because https://www.w3.org/TR/webrtc-identity/ links to it.

That's the "source of truth" for ED URLs and the right place to fix it if people would prefer the latter URL. I filed https://github.com/w3c/webrtc-identity/pull/33

**Comment by foolip** [comment]
Does https://www.w3.org/TR/webrtc-identity/ also need to be published again before this will propagate to browser-specs?

**Comment by tidoust** [comment]
In theory, the ED gets reflected in /TR, which gets ingested by the W3C API. And browser-specs gets the info from the W3C API.
In practice, updating the W3C API directly is doable if publication to /TR is not going to happen any time soon. I'll do it once the ED has been updated.

**Comment by dontcallmedom** [comment]
now fixed
