### ISSUE TITLE
IETF specs provides no `nightly.repository`

### ISSUE THREAD

**Issue by saschanaz** [w3c/browser-specs#331]
It's contradictory to https://github.com/w3c/browser-specs#nightlyrepository.

>The `repository` property is always set.

**Comment by dontcallmedom** [comment]
thanks for pointing it out - I [relaxed the requirement in the code](https://github.com/w3c/browser-specs/pull/325/commits/687e149c501167e2a189c28da28f648f80717fe6) (since the data simply isn't available for some IETF specs) but failed to update the documentation
