### ISSUE TITLE
Add more IETF specs

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#339]
Again, not sure if these are suitable here. Filing what we reference on MDN. (I couldn't see these rendered on httpwg.org)

- https://datatracker.ietf.org/doc/html/rfc2397 (The data URL scheme, for https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)
- https://datatracker.ietf.org/doc/html/rfc8942 (Client hints, for https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH)
- https://datatracker.ietf.org/doc/html/rfc6797 (HSTS, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security)
- https://datatracker.ietf.org/doc/html/rfc7034 (X-Frame-Options, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)
- https://datatracker.ietf.org/doc/html/rfc7578 (For Content-Disposition in multipart/form-data, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)

Also referenced on MDN are the following, but I assume they are not suitable for addition here due to their draft status:
- https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-05 (Digest header)
- https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-expect-ct-08 (Expect-CT header)
- https://datatracker.ietf.org/doc/html/draft-thomson-hybi-http-timeout-03 (Keep-Alive header)

**Comment by dontcallmedom** [comment]
they all look good and relevant; just a note that at least for RFCs whose number is ≥ 8650, I will propose that we switch (not sure yet when) to using `rfc-editor.org` URLs that provide a much nicer HTML rendering (per https://www.rfc-editor.org/format-live/)

**Comment by dontcallmedom** [comment]
re-opening since #341 didn't address the `draft-*` ones. While it feels like the Keep-Alive draft is abandoned (so I'm somewhat skeptical we should add it), the 2 others are definitely relevant.

**Comment by Elchi3** [comment]
> While it feels like the Keep-Alive draft is abandoned (so I'm somewhat skeptical we should add it)

I think we ignore this one. BCD/MDN just referencing https://httpwg.org/specs/rfc7230.html#rfc.section.A.1.2 should be enough, I reckon.
