### ISSUE TITLE
Dealing with experimental IETF RFC

### ISSUE THREAD

**Issue by teoli2003** [w3c/browser-specs#345]
Hi!

I've hit an edge case that sounds legit.

The official spec is RFC 6265 published in 2011 (and listed here).
Since 2017, work is underway to publish an extension https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis.

Every six months or so, a new version is published: https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-08 is the latest, with a validity until the end of the year.

There are widely implemented features available only in the draft (E.g. [Set-Cookie/SameSite on MDN Web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)).

How should we deal with this case? Add https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis as a nightly entry to RFC6265?

**Comment by mnot** [comment]
If I read the README correctly, what's currently done for the W3C is:

* `release` -> anything in `TR`
* `nightly` -> ED

So for the IETF, I think the mapping is:

* `release` -> RFC *or* Internet-Draft
* `nightly` -> Editors' draft (if made available by authors; nothing official)

What this doesn't capture is:

a. the difference between an RFC and an Internet-Draft (in terms of status and mutability)
b. the difference between Internet-Drafts that are on the IETF stream, other streams, or no stream

**Comment by dontcallmedom** [comment]
+1 on looking to add support for this, while figuring out the proper representation in our data model; `nightly` sounds about right, although right now we're abusing that property in the IETF context to also point to the nicer rendering when we know of them. 

I'll note that the bis draft itself has a more useful HTML rendering in https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html

**Comment by hamishwillee** [comment]
Is there any movement or likely movement on this? I wanted to link `SameSite` info from https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-the-samesite-attribute in BCD (https://github.com/mdn/browser-compat-data/pull/13900)

**Comment by dontcallmedom** [comment]
thanks for the ping, this should be available in the next release of browser-spec
