### ISSUE TITLE
Provide version-less titles for series

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/browser-specs#359]
When a consumer (such as BCD/MDN) is not interested in a specific version of a spec, but mostly its latest in the series, there is no good way to refer to the work since the only thing the data provides is the title of the latest version.

Maybe series should have a title - for W3C specs, the series end point of the W3C API provides such a title.

**Comment by dontcallmedom** [comment]
(raised from https://github.com/mdn/content/issues/7651#issuecomment-894091069)

**Comment by tidoust** [comment]
> Maybe series should have a title - for W3C specs, the series end point of the W3C API provides such a title.

I don't see where the W3C provides a version-less title at the series level (or any kind of title at the series level, actually), could you provide an example?

Also, what would the version-less title look like for say, the wai-aria series or the css-color series?

**Comment by dontcallmedom** [comment]
> I don't see where the W3C API provides a version-less title at the series level (or any kind of title at the series level, actually), could you provide an example?

See e.g. https://api.w3.org/specification-series/wai-aria - it has a `name` property set to "Accessible Rich Internet Applications (WAI-ARIA)"

**Comment by tidoust** [comment]
Ah, I was looking for a `title` property as everywhere else. That would have been too simple ;)

I'm not sure whether that series title is automatically generated. For instance, it returns "CSS Color" for the css-color series, and a naive approach would rather generate "CSS Color Module". It could be interesting to align this with the code that we have in place to generate the `shortTitle` property.

Anyway, we could leverage the W3C API whenever possible to create the version-less `series.title` property, and an extended version of the `shortTitle` code that also drops the version number when the series is not known to the W3C API.
