### ISSUE TITLE
Create and publish "release" branch to GitHub Pages

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#38]
Currently, the `master` branch is published to GitHub Pages. That means the `index.json` file may include changes that have not yet been integrated in the NPM package and in the GitHub release. For improved consistency, it would be good to rather maintain a `release` branch that always points at the latest release, and to publish that branch instead.

**Comment by foolip** [comment]
If releases are created by tagging the repository, it would be fairly straightforward to automatically roll a `release` branch forward using a GitHub Action.

**Comment by tidoust** [comment]
With the release workflow introduced while adding support for non-browser specs (PR #496, issue #436), the `web-specs@latest` branch is now the one published under GitHub Pages. It should always point to the commit that gave birth to the latest released version of the `web-specs` package. In other words, the `web-specs@latest` branch acts as the `release` branch envisioned by this old issue.

FWIW, the `index.json` file on the `main` branch is now only updated when tests pass (it used to be updated no matter what).
