### ISSUE TITLE
Reference the W3C Process Document and the W3C Patent Policy

### ISSUE THREAD

**Issue by frivoal** [w3c/browser-specs#390]
Could you add the following two documents:

* shortname: `w3c-process`, undated latest version URL: https://www.w3.org/Consortium/Process/
* shortname: `w3c-patent-policy`, undated latest version  URL: https://www.w3.org/Consortium/Patent-Policy/

They're not actually specs, but they can be useful to reference from specs and other related documents, and are already generated from Bikeshed, so the format shouldn't be surprising.

Speaking of bikeshed, it is bikeshed's planned switch from its current backend to this project that prompted @tabatkins to tell me to file this request here (see https://github.com/w3c/w3process/issues/456#issuecomment-928043280).

**Comment by tidoust** [comment]
Both documents have been added to browser-specs. Definitions should appear in webref in a few hours.

FYI, we will probably move them somewhere else or flag them differently in a not so distant future. In theory, these specs do not belong to browser-specs. In practice, we fully expect that we'll have more and more "non-browser" specs to consider, so we need to figure out whether we can just extend the list here (and possibly rename the project) or whether we need to maintain a separation between browser and non-browser specs. Whatever we end up doing, goal is to make sure that definitions from all specs get captured in cross-reference databases.

**Comment by foolip** [comment]
@tidoust is there a follow-up issue about making it easy to filter these out? This broke https://github.com/foolip/day-to-day/runs/4139803125?check_suite_focus=true and it would be nice to filter them based on what they are (not specs) rather than the URLs.

**Comment by tidoust** [comment]
That's still in our heads but hasn't made much progress so far and had indeed not been captured in an issue so far. I created #436.
