### ISSUE TITLE
specification data missing for spread syntax

### ISSUE THREAD

**Issue by harshvchawla** [w3c/browser-specs#393]
![image](https://user-images.githubusercontent.com/6857593/135808558-1fefee2c-2e89-430b-a491-cf64e7e8c38c.png)

Currently Spread syntax mdn page https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax shows no specification error: `No specification data found for javascript.operators.spread.`

The specification can point to https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-SpreadElement

related to (solved by?) https://github.com/mdn/browser-compat-data/issues/12701

**Comment by dontcallmedom** [comment]
yes, I expect the problem is to be solved in browser-compat-data, not here since the relevant spec is already tracked by browser-specs. Happy to revisit if there is indeed a gap!
