### ISSUE TITLE
CSS Cascading and Inheritance Level 5 not found

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#438]
https://drafts.csswg.org/css-cascade-5/ isn't showing up in webref, and I think it's because of browser-specs.

https://www.w3.org/TR/css-cascade-5/ is the listed URL, but that links to https://drafts.csswg.org/css-cascade-5/, which is Level 4.

As a result, the IDL in https://drafts.csswg.org/css-cascade-5/#idl-index isn't showing up in webref.

**Comment by dontcallmedom** [comment]
I've filed https://github.com/w3c/csswg-drafts/issues/6841 - ideally, this would be fixed upstream

**Comment by dontcallmedom** [comment]
so browser-specs now has the proper link to css-cascade-5, but reffy doesn't extract the IDL from it, presumably because it is stuck between css-cascade-4 which acts as "latest", and css-cascade-6 which is the "delta" and thus gets special treatment in reffy.

@tidoust, thoughts?

**Comment by tidoust** [comment]
No, it's just that the new version of browser-specs was not yet the one used in Reffy. I just made the update. Reffy will create a `css-cascade.idl` file in webref next time it runs with the IDL defined in level 5.

**Comment by tidoust** [comment]
Now done, see [`css-cascade.idl`](https://github.com/w3c/webref/blob/1ece7fb8bd46e6172a167a56a19c5313b8ea71c0/ed/idl/css-cascade.idl) in webref. Closing the issue accordingly.
