### ISSUE TITLE
Are repository migrations automatically reflected here?

### ISSUE THREAD

**Issue by saschanaz** [w3c/browser-specs#440]
[w3c/validate-repos now reflects the migration of w3c/web-locks](https://github.com/w3c/validate-repos/commit/31d1f1eef24426f48c519cb9fb2cba0f566fca40) but it seems neither of `npm run build` nor `node src/find-specs.js` reflects that. Specifically, the new data does not pass `!spec.find(s => hasMoreRecentLevel` check inside `hasUntrackedURL`.

Am I doing something wrong?

**Comment by dontcallmedom** [comment]
it's bug indeed; I've filed #441 which hopefully will help
