### ISSUE TITLE
Add WebAssembly exception handling spec?

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#508]
https://webassembly.github.io/exception-handling/js-api/index.html is a spec that describes new JavaScript built-ins `Exception` and `Tag`. They are shipping in Safari 15.2.

BCD PR: https://github.com/mdn/browser-compat-data/pull/14910

Add this spec to browser-specs?

**Comment by dontcallmedom** [comment]
Hmm... The situation is a bit confusing: https://webassembly.github.io/exception-handling/js-api/index.html seems to be a superset of https://webassembly.github.io/spec/js-api/, but uses the same "this version" and "TR latest" URIs. I'm not quite sure why it exists separately from the main spec in the first place.

@ms2ger can you help us figure out how we should handle these two documents?

**Comment by Ms2ger** [comment]
This is how the wasm cg works, for better or worse: every proposal has its own fork of the full spec repo, so at any point, there's a number of different (and hopefully compatible) supersets of the main spec floating around. I tried to fix the urls here: https://github.com/WebAssembly/exception-handling/pull/199.

**Comment by dontcallmedom** [comment]
Thanks for the explanation, which I guess implies we may have to deal with other similar cases.

When does a proposal gets merged in the main spec? Is it linked to implementation adoption as for Ecmascript?
