### ISSUE TITLE
Wrong nightly URL for Media Queries

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#52]
The URL in browser-specs is http://dev.w3.org/csswg/css3-mediaqueries/, but should be https://drafts.csswg.org/mediaqueries-3/.

**Comment by tidoust** [comment]
Fixed upstream in W3C systems, picked up in https://github.com/w3c/browser-specs/commit/77ecc47cb88d95766c0383d0aca62d48d313b527 and released in [v1.2.0](https://github.com/w3c/browser-specs/releases/tag/1.2.0)
