### ISSUE TITLE
Wrong nightly URL for WAI-ARIA

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#53]
It's https://rawgit.com/w3c/aria/master/, but should be https://w3c.github.io/aria/.

**Comment by tidoust** [comment]
Fixed upstream in W3C systems, picked up in https://github.com/w3c/browser-specs/commit/77ecc47cb88d95766c0383d0aca62d48d313b527 and released in [v1.2.0](https://github.com/w3c/browser-specs/releases/tag/1.2.0)
