### ISSUE TITLE
CSS Speech nightly URL missing

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#54]
The `css-speech-1` entry should have a nightly URL https://drafts.csswg.org/css-speech-1/.

**Comment by foolip** [comment]
I don't think it's related, but I sent https://github.com/w3c/csswg-drafts/pull/5118 to correct an error in the spec's metadata.

**Comment by tidoust** [comment]
Fixed upstream in W3C systems, picked up in https://github.com/w3c/browser-specs/commit/96ac4f51ff9e07ac99ced932b212fdf8232f6bc0 and released in [v1.2.0](https://github.com/w3c/browser-specs/releases/tag/1.2.0)
