### ISSUE TITLE
Add missing specs from day-to-day

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#58]
After https://github.com/foolip/day-to-day/issues/85 I've identified these as still missing from browser-specs.

WICG:
- [x] [Accelerated Text Detection in Images](https://wicg.github.io/shape-detection-api/text.html)
- [ ] <s>[Accessibility Object Model](https://wicg.github.io/aom/spec/)</s>
- [x] [Client Hints Infrastructure](https://wicg.github.io/client-hints-infrastructure/)
- [x] [Origin-bound one-time codes delivered via SMS](https://wicg.github.io/sms-one-time-codes/)
- [x] [Web Budget API](https://wicg.github.io/budget-api/)

TC39:
- [ ] [ECMAScript Internationalization API Specification](https://tc39.es/ecma402/)
- [ ] [ECMAScript Language Specification](https://tc39.es/ecma262/)

Miscellaneous:
- [ ] <s>[execCommand](https://w3c.github.io/editing/execCommand.html)</s>
- [x] [Image Resource](https://w3c.github.io/image-resource/)
- [x] [SVG Integration](https://svgwg.org/specs/integration/)
- [x] [SVG Paths](https://svgwg.org/specs/paths/)
- [x] [WebAssembly](https://webassembly.github.io/spec/core/)

**Comment by foolip** [comment]
For WICG, I suspect the correct "pipeline" simply does not exist, so new specs will need to be handled manually.

@tidoust is https://github.com/WICG/admin/blob/gh-pages/biblio.json the upstream source for WICG? If so the problem to be solved is ensuring that gets updated.

**Comment by tidoust** [comment]
> @tidoust is https://github.com/WICG/admin/blob/gh-pages/biblio.json the upstream source for WICG? If so the problem to be solved is ensuring that gets updated.

Yes, that file is used to populate Specref, which browser-specs uses in turn to retrieve info about WICG specs.

**Comment by tidoust** [comment]
Thanks @foolip! I prepared #64 that adds most of these specs.

The [Accessibility Object Model](https://wicg.github.io/aom/spec/) spec is mostly a wrapper to other specs. Should these other specs be added as well?

Link to execCommand is broken. I see [execCommand](https://w3c.github.io/editing/docs/inactive/execCommand.html) but that spec is flagged as inactive. Has work resumed elsewhere? If not, given all the warnings in the spec, why should it be included?

I haven't included TC39 specs for now, as I'd like to check how Reffy reacts to these specs first.

**Comment by foolip** [comment]
I think AOM was more of a full spec when I looked at it last, I'll drop it from day-to-day.

execCommand I'm listing more on principle that *some* spec should definitely define it, and this one does. But still, the warning box is true. I can't argue for including it.

**Comment by foolip** [comment]
https://github.com/w3c/browser-specs/issues/139 covers the remaining part of this issue, closing.
