### ISSUE TITLE
Detect publication as Note / Discontinued draft for W3C specs

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/browser-specs#615]
as in #614

**Comment by tidoust** [comment]
We now record the status of published W3C specifications and automatically filter out discontinued drafts from the browser-specs package. We do keep a few discontinued drafts in the web-specs list on purpose for cross-referencing as some specs may want to talk about what happened a long time ago in a galaxy far far away (that should only ever be needed in informative parts of specs though).
