### ISSUE TITLE
Do we need customized context menu?

### ISSUE THREAD

**Issue by xkol** [w3c/browser-specs#685]
I want to implement the new feature of customized context menu in the browser. This feature allow web deveploers to define customized native menu,it can make the website like a native app.
However, i found the chrome and firefox browser support it in history.
Unfortunately, they removed the context menu feature from browser due to lack of implementer interest.
I want to know wheather this feature has risk? for example, web customer believe the native browser code, but the website could execute some actions themselves.

**Comment by dontcallmedom** [comment]
this repository isn't meant to ask question about web specifications - we merely curate a list of such specifications.

With regard to context menu and its removal, see https://github.com/whatwg/html/issues/2730 and https://bugs.chromium.org/p/chromium/issues/detail?id=87553#c64

**Comment by xkol** [comment]
> this repository isn't meant to ask question about web specifications - we merely curate a list of such specifications.
> 
> With regard to context menu and its removal, see [whatwg/html#2730](https://github.com/whatwg/html/issues/2730) and https://bugs.chromium.org/p/chromium/issues/detail?id=87553#c64

Thank you, i will look up these documents.
