### ISSUE TITLE
Cover FIDO Client to Authenticator Protocol?

### ISSUE THREAD

**Issue by saschanaz** [w3c/browser-specs#708]
That spec has a small bit of Web IDL that extends Web Authentication: https://fidoalliance.org/specs/fido-v2.1-rd-20210309/#idl-index

Perhaps worth having them?

**Comment by tidoust** [comment]
No problem adding the spec but we're currently investigating why the spec, which is supposed to define a protocol, contains IDL definitions that should perhaps rather be directly integrated in the Web Authentication spec. We'll add the spec once we're clearer on what this API is and thus on where the spec fits in the list.

**Comment by dontcallmedom** [comment]
I checked with my contact at the FIDO alliance:
> The spec uses WebIDL mainly as a formatting convenience. None of it is intended for use by the web client.

So I think this points towards not including the spec in (or at least not as a browser spec)

**Comment by saschanaz** [comment]
Well, Gecko is using it, interesting? https://searchfox.org/mozilla-central/rev/cefb4bc274c71aa4badbec09da9c056fd8ca4472/dom/webidl/WebAuthentication.webidl#132

**Comment by dontcallmedom** [comment]
do you know if anything is plugged in Gecko to react to that dictionary member?

**Comment by saschanaz** [comment]
Yes, https://phabricator.services.mozilla.com/D31093 is the full patch to implement this extension, citing Chromium supporting it, which is shown in https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/credentialmanagement/authentication_extensions_client_inputs.idl;l=16-17;drc=70a2415c213b2324d481133c2d3b6fdbb2b45a0a and https://source.chromium.org/chromium/chromium/src/+/main:out/mac-Debug/gen/third_party/blink/renderer/bindings/modules/v8/v8_authentication_extensions_client_inputs.h?q=hmacCreateSecret.

I don't see WPT for this, though.

**Comment by dontcallmedom** [comment]
filed https://github.com/w3c/webauthn/issues/1809 as a follow up

**Comment by dontcallmedom** [comment]
If I interpret https://github.com/w3c/webauthn/issues/1809#issuecomment-1258004773 correctly, it looks like we should indeed add CTAP as a browser spec - @tidoust, thoughts?

**Comment by tidoust** [comment]
Sounds good, let's add it then. I don't think we have any other spec from the FIDO Alliance though, note this will likely require a bit of logic update here and there, be it only to set the `organization` properly.

**Comment by tidoust** [comment]
Closing as done. Spec is in the latest version of browser-specs/web-specs packages.
