### ISSUE TITLE
Run script to find list of specs periodically

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#71]
See discussion in https://github.com/w3c/browser-specs/pull/70#issuecomment-642508765

Goal is to set up a regular GitHub action to run the script that finds new specs periodically (once per week?), and have it raise a GitHub issue with new specs it may find.

Note that the action should also check `lastreviewed` dates in `monitor-repos.json` and force a periodic review for entries that have not been checked in the last 3 months or so.

**Comment by dontcallmedom** [comment]
implemented in #76
