### ISSUE TITLE
Current spec for Client Hint Reliability (i.e. `Critical-CH`)?

### ISSUE THREAD

**Issue by chrisdavidmills** [w3c/browser-specs#788]
Hi there,

I'm currently in the process of documenting the `Critical-CH` header on MDN, but I can't find a reliable current spec document for it. This repo doesn't contain anything, as far as I can tell, and any specs I can find (e.g. https://datatracker.ietf.org/doc/html/draft-davidben-http-client-hint-reliability) seem to be expired or obsolete. Does anyone have any useful information about this?

Thanks.

**Comment by tidoust** [comment]
I don't have useful information about the spec but I think it's fine to add the IETF draft to the list: even though it is currently "expired", it does not seem to have been abandoned. The underlying header is also supported in Chrome, I believe. That's good enough for browser-specs, especially if it is also useful for MDN. I'll prepare a pull request.

**Comment by chrisdavidmills** [comment]
Thanks @tidoust , much appreciated!
