### ISSUE TITLE
Add spec for Cookies Having Independent Partitioned State (CHIPS)?

### ISSUE THREAD

**Issue by chrisdavidmills** [w3c/browser-specs#822]
Hello, me again ;-)

I'm currently adding MDN documentation for this feature, and the latest spec I can find is https://datatracker.ietf.org/doc/html/draft-cutler-httpbis-partitioned-cookies-01. But when I try to include it as the spec URL in BCD, it complains. Can you add it to this repo?

**Comment by tidoust** [comment]
Done and released in latest versions of the web-specs and browser-specs packages.
