### ISSUE TITLE
Exclude CSS specs with `Warning: Not Ready`

### ISSUE THREAD

**Issue by cdoublev** [w3c/browser-specs#828]
The Bikeshed metadata entry `Warning: Not Ready` is specified for [CSS Color 6](https://github.com/w3c/csswg-drafts/blob/main/css-color-6/Overview.bs#L7) and CSS Backgrounds 4. The result is a banner with the warning: 

> **Not Ready For Implementation**
>
> This spec is not yet ready for implementation. It exists in this repository to record the ideas and promote discussion.
>
> Before attempting to implement this spec, please contact the CSSWG at www-style@w3.org.

Do these specs intentionally match the Spec selection criteria despite this warning?

`<wcag2()>` is extracted without a `value` by `reffy` (cf. [`webref`](https://github.com/w3c/webref/blob/78dd48795f981103842e43eb7b40f8a0ce506ba5/ed/css/css-color-6.json#L29)) because it is missing a proper production `wcag2() = wcag2([<number> | [ aa | aaa ] && large? ])`. If I file an issue on `w3c/csswg-drafts`, it will probably be ignored because the spec is not ready for implementation.

In CSS Color 6, it does not really matter because the spec does not replace definitions existing in previous versions of the spec. In CSS Backgrounds 4, some property definitions are replaced, though this spec does not seem to have any definition issue.

**Comment by cdoublev** [comment]
Hmm, I found  #56 and #279. So the decision to crawl a spec that is not ready depends to subjective criteria. Sorry for missing them.

Fwiw, I noted the following specs:

- CSS Backgrounds 4 is not ready and there is 2 open issues for problematic definitions
  - https://github.com/w3c/csswg-drafts/issues/7367
  - https://github.com/w3c/csswg-drafts/issues/7376
- CSS Color 6 is not ready and I have not already reported the issue commented above
- CSS Color HDR status is `Unofficial Draft` and has not been updated since 9 months
- CSS Conditional Values status is `Unofficial Draft` and has not been updated since 1 year
- CSS GPCM 4 is not ready and its re-definition of `<content-list>` (also defined in CSS GCPM 3) would deserve an issue
- CSS Table 3 is not ready but its definitions seem ok to me
- Non-element Selectors is not ready and has not been updated since 2 years

I cannot tell whether which features from these specs are currently experimented in browsers. I think some properties of CSS Backgrounds 4 are implemented in some of them.

**Comment by cdoublev** [comment]
Thank you for your answer, your suggestions, and for taking care of reporting the problem with `wcag2`.

I understand that a specification that is not ready for implementation may still be relevant for the web platform. Safari and Firefox seem to have implemented `background-position-*` defined in CSS Background 4 since a long time, and some may even be written at the same time as they are implemented.

Anyway, since new specs are not frequently added, I think I can manually monitor/select/exclude them. Thanks again.

**Comment by cdoublev** [comment]
Aside: your [commit](https://github.com/w3c/csswg-drafts/commit/1ab667ff844d215c15319b4ed2da32082f98817d) does not seem to have fixed `wcag2()`: it still has no `value` (argument definition).

**Comment by tidoust** [comment]
> Aside: your [commit](https://github.com/w3c/csswg-drafts/commit/1ab667ff844d215c15319b4ed2da32082f98817d) does not seem to have fixed `wcag2()`: it still has no `value` (argument definition).

Right, see https://github.com/w3c/reffy/issues/1146#issuecomment-1381697923
