### ISSUE TITLE
css-device-adapt is renamed to css-viewport

### ISSUE THREAD

**Issue by tabatkins** [w3c/browser-specs#837]
The older CSS Device Adaptation spec was retired, and most of its content moved to a new CSS Viewport spec. The Reffy data correctly recognizes that <https://drafts.csswg.org/css-viewport/> is the ED for <https://www.w3.org/TR/css-device-adapt-1/>, but still has them categorized under the "css-device-adapt-1" shortname.

At some point in the near future (should happen this year) we'll publish a /TR of css-viewport, thus completely replacing the older device-adapt name. Can we change the shortname in the data now?

(This was reported by a Bikeshed user trying to link to a section in css-viewport and getting a "no spec of that name" error.)

**Comment by tidoust** [comment]
"css-device-adapt-1" is now gone, replaced by "css-viewport". The update has already cascaded to bikeshed-data as far as I can tell.
