### ISSUE TITLE
Publish valid fragments and sub-pages for specs

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#931]
In https://github.com/web-platform-dx/feature-set/pull/122 @ddbeck did some work to validate URLs on top of browser-specs. We assume that specs that end with "/multipage/" allow some extra trailing bits, and also spec URLs can have fragment parts.

It would be great if browser-specs had the necessary information to judge if a spec link is valid, or indeed helpers that implement those checks.

Examples of spec URLs that aren't trivial to vet based on only browser-specs are https://html.spec.whatwg.org/multipage/popover.html and https://w3c.github.io/csswg-drafts/css-grid/#subgrids.

**Comment by tidoust** [comment]
For sub-pages, I don't really understand what you're looking for: browser-specs already lists sub-pages of multipage specs in a `pages` property, see. e.g. the [`pages` property for the HTML spec](https://github.com/w3c/browser-specs/blob/74cbb16227a54ec95773386783444d9045dc5e47/index.json#L1697). This should allow you to validate that a URL targets an actual spec page. Is anything missing?

For fragments, I don't have a solution that would only involve browser-specs but I note that fragment IDs are extracted by the crawler and published in Webref, e.g. for CSS Grid level 2: https://github.com/w3c/webref/blob/main/ed/ids/css-grid-2.json (the absolute URLs use the leveled URL but it's relatively easy to assess whether a non-leveled fragment exists by looking at what level is the `currentSpecification`). Would that provide the info you need?

**Comment by ddbeck** [comment]
Thank you for the extra info and suggestions, @tidoust!

> For sub-pages, I don't really understand what you're looking for: browser-specs already lists sub-pages of multipage specs in a `pages` property, see. e.g. the [`pages` property for the HTML spec](https://github.com/w3c/browser-specs/blob/74cbb16227a54ec95773386783444d9045dc5e47/index.json#L1697).

I didn't realize that `pages` property was available. This provided an immediate solution to URLs, which is now merged into the feature-set validation.

> For fragments, I don't have a solution that would only involve browser-specs but I note that fragment IDs are extracted by the crawler and published in Webref, e.g. for CSS Grid level 2: https://github.com/w3c/webref/blob/main/ed/ids/css-grid-2.json (the absolute URLs use the leveled URL but it's relatively easy to assess whether a non-leveled fragment exists by looking at what level is the `currentSpecification`). Would that provide the info you need?

I think this will require a little experimentation for feature-set—I'd be curious to know whether the fragments are reliably equivalent in leveled and unleveled specs—but this is a very helpful place to start. 👍

**Comment by tidoust** [comment]
> I think this will require a little experimentation for feature-set—I'd be curious to know whether the fragments are reliably equivalent in leveled and unleveled specs—but this is a very helpful place to start. 👍

The unleveled spec is an alias to one of the levels, so fragments are the same in the unleveled spec and in the targeted leveled spec. There is no strong guarantee that fragments remain the same between levels though, so unleveled fragments that used to be correct may become incorrect when the underlying level changes. That usually does not happen for fragments that matter...

**Comment by foolip** [comment]
Thanks @tidoust, I didn't know pages were already provided.

**Comment by tidoust** [comment]
Closing this as supported (for pages) or out of scope for browser-specs but in scope of webref (for fragments).
Feel free to reopen or to raise another issue if needed!
